config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # lister les taches
  get "tasks", to: "tasks#index"
  # ajouter une nouvelle tache
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  # afficher les détails
  get "tasks/:id", to: "tasks#show", as: :task
  # éditer (marqué comme terminé/mettre à jour)
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  #  supprime une tache
  delete "tasks/:id", to: "tasks#destroy", as: :destroy_task


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy

    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
     <div class="container">
      <%= yield %>
     </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= check_box_tag(:completed) %>
  <%= label_tag(:completed, "It's done") %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% @tasks.each do |task| %>
  <li> <%= link_to task["title"], task_path(task["id"])%> </li>
<% end %>

<%= link_to "Add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<!-- app/views/task/new.html.erb -->
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= check_box_tag(:completed) %>
  <%= label_tag(:completed, "It's done") %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Detail</h1>

 <%= link_to edit_task_path(@task), class: "text-black" do %>
    <i class="fa-solid fa-pen-to-square"></i>
  <% end %>

 <%= link_to destroy_task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-black" do %>
    <i class="fa-solid fa-trash"></i>

  <% end %>

<h2><%= @task.title %> </h2>
<p><%= @task.details %></p>

<%= link_to "Back to tasks", tasks_path %>